### ISSUE TITLE
image

### ISSUE THREAD

**Issue by aooiuu** [aooiuu/any-reader-vscode#1]

**Comment by aooiuu** [comment]
![1](https://github.com/aooiuu/any-reader-vscode/assets/28108111/fff2e255-5e09-4bff-b45c-78070dce8afc)

**Comment by weixiaoxiang** [comment]
‘any-reader-vscode’在插件市场搜索不到？

**Comment by aooiuu** [comment]
> ‘any-reader-vscode’在插件市场搜索不到？

搜 `any-reader`, 下个版本我把关键词优化下
